name: blase_pt1p11
channels:
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - nvidia::cudatoolkit=11.3
  - python=3.9
  - pytorch::pytorch
  - numpy
  - scipy
  - matplotlib
  - astropy>=5.0
  - tqdm
  - pandas
  - jupyter
  - ipython
  - seaborn
  - pyarrow
  - torchvision
  - torchaudio
  - pytest
  - pip
  - cmake
  - sphinx
  - nbsphinx
  - sphinx-gallery
  - sphinx-book-theme
  - specutils
  - importlib_resources
  - tensorflow
  - black
  - pip:
      - tensorboard
